In [354]:
import pandas as pd
import numpy as np
import pathlib

In [358]:
file_path = pathlib.Path("/Users/piotrkedzierski/Documents/Programowanie/Mamusia/19062026 axe txe in genome genes.xlsx")

df = pd.read_excel(file_path)

df

,Application: Tecan i-control,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Tecan i-control , 2.0.10.0",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Device: infinite 200Pro,NaN,NaN,NaN,Serial number: 2411006888,NaN,NaN,NaN,Serial number of connected stacker:,NaN,NaN,NaN
1,Firmware: V_5.40_03/24_InfiniteRX (Mar 27 2024...,NaN,NaN,NaN,"MAI, V_5.40_03/24_InfiniteRX (Mar 27 2024/11.4...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date:,19.06.2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Time:,09:47:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
241,H12,1085,1768.0,3446.0,6989,17936,39624.0,78351.0,129345,212541.0,200124.0,176525.0
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,End Time:,19.06.2026 15:14:42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [417]:
ode = df[45:141:1]
lux = df[146:242:1]

cols = ode.columns

for col in cols[1:]:
    ode[col] = pd.to_numeric(ode[col], errors="coerce")
    lux[col] = pd.to_numeric(lux[col], errors="coerce")

/var/folders/fz/c2n2l12s2rxd6wkgx__1jp400000gn/T/ipykernel_56203/3031660865.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ode[col] = pd.to_numeric(ode[col], errors="coerce")
/var/folders/fz/c2n2l12s2rxd6wkgx__1jp400000gn/T/ipykernel_56203/3031660865.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lux[col] = pd.to_numeric(lux[col], errors="coerce")

In [418]:
numeric_cols = ode.select_dtypes(include="number").columns

lux_by_ode = ode.copy()

lux_by_ode[numeric_cols] = lux[numeric_cols].div(ode[numeric_cols], fill_value=1)

lux_by_ode

,Application: Tecan i-control,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Tecan i-control , 2.0.10.0",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
45,A1,9.033424,9.025271,7.930214,6.146282,4.363002,3.216468,2.754062,2.538071,2.352388,2.236136,2.246182
46,A2,9.140768,9.124088,7.917656,6.657790,4.899559,3.556188,2.911208,2.685285,2.556237,2.463661,2.362949
47,A3,8.912656,9.082652,8.319468,6.720430,4.861449,3.453038,2.871088,2.614379,2.458815,2.391200,2.289377
48,A4,9.337068,9.208103,8.554320,7.225433,5.425936,3.891051,3.008424,2.697599,2.515723,2.411382,2.311070
49,A5,9.319665,9.337068,8.591065,7.246377,5.411255,3.915427,3.047851,2.748763,2.574003,2.485090,2.374733
...,...,...,...,...,...,...,...,...,...,...,...,...
136,H8,9.310987,9.363296,9.000900,8.116883,6.675567,5.257624,4.514673,4.098361,3.810976,3.606203,3.467406
137,H9,9.157509,9.082652,8.795075,7.955450,6.464124,5.141388,4.458315,4.063389,3.786445,3.580379,3.437608
138,H10,9.451796,9.727627,9.633911,9.225092,9.009009,8.156607,6.775068,5.540166,4.780115,4.317789,4.037142
139,H11,9.478673,9.737098,9.532888,9.216590,8.960574,8.090615,6.738545,5.561735,4.814637,4.347826,4.070004
140,H12,9.372071,9.661836,9.615384,9.354537,9.140768,8.460237,7.215007,5.931198,5.073567,4.568296,4.249894

In [428]:
lux[numeric_cols].div(ode[numeric_cols], fill_value=1)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Tecan i-control , 2.0.10.0",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
45,9.033424,9.025271,7.930214,6.146282,4.363002,3.216468,2.754062,2.538071,2.352388,2.236136,2.246182
46,9.140768,9.124088,7.917656,6.657790,4.899559,3.556188,2.911208,2.685285,2.556237,2.463661,2.362949
47,8.912656,9.082652,8.319468,6.720430,4.861449,3.453038,2.871088,2.614379,2.458815,2.391200,2.289377
48,9.337068,9.208103,8.554320,7.225433,5.425936,3.891051,3.008424,2.697599,2.515723,2.411382,2.311070
49,9.319665,9.337068,8.591065,7.246377,5.411255,3.915427,3.047851,2.748763,2.574003,2.485090,2.374733
...,...,...,...,...,...,...,...,...,...,...,...
237,6078.000000,9353.000000,20774.000000,47486.000000,96511.000000,150625.000000,194159.000000,163109.000000,145646.000000,130728.000000,117669.000000
238,6315.000000,9739.000000,20607.000000,48377.000000,98883.000000,150306.000000,190544.000000,159561.000000,142048.000000,128726.000000,114121.000000
239,966.000000,1684.000000,3356.000000,7370.000000,18170.000000,39398.000000,77286.000000,134138.000000,220844.000000,219526.000000,192149.000000
240,984.000000,1660.000000,3285.000000,7339.000000,18425.000000,39975.000000,77763.000000,131215.000000,213980.000000,214461.000000,187810.000000
241,1085.000000,1768.000000,3446.000000,6989.000000,17936.000000,39624.000000,78351.000000,129345.000000,212541.000000,200124.000000,176525.000000

In [433]:
ode[numeric_cols].loc(1)